apiVersion: apps/v1
kind: Deployment

metadata:
  name: cartservice
  namespace: freshmart
  labels:
    app: cartservice

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cartservice

  template:
    metadata:
      labels:
        app: cartservice

    spec:
      containers:
        - name: cartservice
          image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/cartservice:v0.10.6
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 7070

          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"